//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOODamage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InnerCategory
    {
        public int IdInnerCategory { get; set; }
        public int MainCategory { get; set; }
        public int AddCategory { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductCategory ProductCategory1 { get; set; }
    }
}
