//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOODamage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOnWareHouse
    {
        public int IdProdOnWareHouse { get; set; }
        public int IdProduct { get; set; }
        public int IdWareHouse { get; set; }
        public int Qty { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual WareHouse WareHouse { get; set; }
    }
}
